### ISSUE TITLE
HMMSearch block and freeze

### ISSUE THREAD

**Issue by jpjarnoux** [althonos/pyhmmer#61]
Hi

As explained in your documentation, I'm trying to align multiple HMM (736) against a digitalized database of sequences (32196).  I don't know why, but it looks like pyhmmer is freezing during hmmsearch. When I force to stop the command I have this message: 

```
Traceback (most recent call last):
  File "/env/cns/home/jarnoux/.conda/envs/panorama/bin/panorama", line 8, in <module>
    sys.exit(main())
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/main.py", line 168, in main
    panorama.annotate.launch(args)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 276, in launch
    annot_pangenomes(pangenomes=pangenomes, source=args.source, table=args.table,
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 256, in annot_pangenomes
    pangenomes2metadata = annot_pangenomes_with_hmm(pangenomes, hmm, mode, bit_cutoffs, threads, disable_bar)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 224, in annot_pangenomes_with_hmm
    pangenome2annot[pangenome.name] = annot_with_hmm(pangenome, hmms, hmm_df, mode, bit_cutoffs,
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/hmm_search.py", line 261, in annot_with_hmm
    res = annot_with_hmmsearch(hmms, gf_sequences, meta, bit_cutoffs, threads, disable_bar)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/hmm_search.py", line 195, in annot_with_hmmsearch
    for top_hits in pyhmmer.hmmsearch(hmm_list, gf_sequences, cpus=threads, **options):
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 505, in _multi_threaded
    query_queue.put(chore)  # <-- blocks if too many chores in queue
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/queue.py", line 140, in put
    self.not_full.wait()
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```

I tried another HMM database, and everything works well. So, It could come from the HMM profile, but they are from CasFinder. That's why I do not understand from where it's coming. 

I also tried to launch directly hmmer and it looks like everything works as expected.

**Comment by althonos** [comment]
There is likely a background issue that is not being reported, try using `v0.10.7` I just put out, and hopefully you should get an actual detail of the error.

**Comment by jpjarnoux** [comment]
Hi,
With the new version I have this error:
```
Traceback (most recent call last):█▋       | 26/99 [00:01<00:04, 14.88hmm/s]
  File "/env/cns/home/jarnoux/.conda/envs/panorama/bin/panorama", line 8, in <module>
    sys.exit(main())
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/main.py", line 168, in main
    panorama.annotate.launch(args)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 276, in launch
    annot_pangenomes(pangenomes=pangenomes, source=args.source, table=args.table,
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 256, in annot_pangenomes
    pangenomes2metadata = annot_pangenomes_with_hmm(pangenomes, hmm, mode, bit_cutoffs, threads, disable_bar)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/annotate.py", line 224, in annot_pangenomes_with_hmm
    pangenome2annot[pangenome.name] = annot_with_hmm(pangenome, hmms, hmm_df, mode, bit_cutoffs,
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/hmm_search.py", line 265, in annot_with_hmm
    res = annot_with_hmmsearch(hmms, gf_sequences, meta, bit_cutoffs, threads, disable_bar)
  File "/env/export/cns_n02_agc/agc/proj/PANORAMA/panorama/annotate/hmm_search.py", line 200, in annot_with_hmmsearch
    for top_hits in pyhmmer.hmmsearch(hmm_list, gf_sequences, cpus=threads, callback=hmmsearch_callback, **options):
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 520, in _multi_threaded
    yield results[0].get()
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 122, in get
    raise self.exception
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 215, in run
    hits = self.process(chore.query)
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 231, in process
    hits = self.query(query)
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/utils.py", line 70, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/env/cns/home/jarnoux/.conda/envs/panorama/lib/python3.10/site-packages/pyhmmer/hmmer.py", line 259, in _
    return self.pipeline.search_hmm(query, self.targets)
  File "pyhmmer/plan7.pyx", line 5656, in pyhmmer.plan7.Pipeline.__pyx_fuse_1search_hmm
  File "pyhmmer/plan7.pyx", line 5731, in pyhmmer.plan7.Pipeline.search_hmm
  File "pyhmmer/plan7.pyx", line 5926, in pyhmmer.plan7.Pipeline._search_loop
pyhmmer.errors.MissingCutoffs: Model is missing bitscore cutoff required by pipeline
```
So I checked, and it was my HMM, so it was a good idea to make the error more detailed. Maybe you could add the query name to find which profile is causing the error.

PS: I don't know why HMMER worked with this profile; maybe I didn't use it correctly.

**Comment by althonos** [comment]
Are you using annotation with `bit_cutoffs="trusted"` or something? If so, did you run HMMER with `hmmsearch --cut_tc` to have the same behaviour?

I'll see if I can detail the error, since this is coming from a hot path of the pipeline (the `Pipeline._search_loop` function) which runs without the GIL accessing the responsible Python object may not be possible, but maybe I can at least get the same of the HMM if any.

**Comment by jpjarnoux** [comment]
I was using bit_cutoffs='gathering', so yes, for hmmer, there is an option `--cut_ga` if I remember. So that's why it worked with HMMER I tested too quickly. 
Anyway, thanks again for your quick reply and the help.

**Comment by althonos** [comment]
No worries 👍 I'll also change the error message so it contains the model name.
