### ISSUE TITLE
Could not parse file: Line 20: illegal character -

### ISSUE THREAD

**Issue by JediKnightChan** [althonos/pyhmmer#7]
It can't parse FASTA files with "-" symbol, though it's present in hmm.alphabet.symbols

```python
            with pyhmmer.plan7.HMMFile(model_filepath) as hmm_file:
                hmm = next(hmm_file)

            for record in SeqIO.parse(sequences_filepath, "fasta"):
                # Can't create Digital Sequence here :(
                pass

            with pyhmmer.easel.SequenceFile(sequences_filepath) as seq_file:
                seq_file.set_digital(hmm.alphabet)
                sequences = list(seq_file) # Producing error

            pipeline = pyhmmer.plan7.Pipeline(hmm.alphabet)
            hits = pipeline.search_hmm(hmm, sequences)
```

```python
Traceback (most recent call last):
  File "/home/jediknight/Documents/Nonribosomal-Peptides/hmm.py", line 110, in <module>
    acc = test_models()
  File "/home/jediknight/Documents/Nonribosomal-Peptides/hmm.py", line 76, in test_models
    sequences = list(seq_file)
  File "pyhmmer/easel.pyx", line 3683, in pyhmmer.easel.SequenceFile.__next__
  File "pyhmmer/easel.pyx", line 3724, in pyhmmer.easel.SequenceFile.read
  File "pyhmmer/easel.pyx", line 3791, in pyhmmer.easel.SequenceFile.readinto
ValueError: Could not parse file: Line 20: illegal character -
```

**Comment by althonos** [comment]
Hi @JediKnightChan !

The Easel developers have added a check to make sure that the input files don't contain `-` because that's normally a gap marker, which means you're probably trying to read from a MSA. However, I was able to add a patch for this to let you simply ignore the character (`AT-GC` in the file would be read as `ATGC`) so I'll add that to a next release.

**Comment by althonos** [comment]
Just released `v0.4.4`. Now you can enable ignoring gap characters while reading a sequence. Just set the `ignore_gaps` parameter to `True` when creating the sequence file object and you'll be good to go:
```python
with pyhmmer.easel.SequenceFile(sequences_filepath, ignore_gaps=True) as seq_file:
    seq_file.set_digital(hmm.alphabet)
    sequences = list(seq_file) # Producing error
```

**Comment by jeanrjc** [comment]
Hello @althonos 

`ignore_gaps` has been deprecated, how can we achieve the same behavior ? 

Thanks

**Comment by althonos** [comment]
Hi @jeanrjc,

You can use the `afa` (aligned FASTA) format with `SequenceFile`:

```python
with pyhmmer.easel.SequenceFile("sequences.fasta", format="afa") as seq_file:
   ...
```
